### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by eddiepiazza** [WebCrew/PrettyHub-HumHub-Theme#1]
Hi, I installed your them to try it and I had 500 site error, impossible to access. Is good that I am already experienced in this kind of cases and I switched first to HumHub default theme, duplicated page for activate yours and after check is not working come back to my them from my page backup.

Is really strange because this is not the first theme who give me problems like this. I have HH 1.1.1 and I can´t understand why this is happening... maybe uncompatibility with some modules?

**Comment by WebCrew** [comment]
lol thanks for the info, but it is not ready to use right now. Its in development and I`ll write a README if its done.
But you can use my other theme called https://github.com/WebCrew/TodGmbH-HumHub-Theme

**Comment by eddiepiazza** [comment]
I used your other one that looks nice but has a problem with login. My community is private and needs to be registered to access. Seems that you have not implemented this functionality.

This is what actually I am using as login: www.gropedia.com

**Comment by WebCrew** [comment]
Yes You are right, it is not implemented. My theme needs one space open for guests also. Otherwise You can not see the login/registration button :+1: 

So best is You make one space open for info or so. I can not rewrite the theme because it is the way it should work. It is my private theme and I only open it for the HumHub users to use too.

**Comment by eddiepiazza** [comment]
Ah thanks. Last question, is it possible to extract the login page from my actual theme and replace or add it into your theme? I already try to include login.php file but seems not so simple.

**Comment by WebCrew** [comment]
To be honest, I`m not good if it comes to PHP or Yii programming, so I have to say sorry mate I can not help You. But I`m sure You`ll find help at the HH community.

Kind regards and I wish You much success :)
